config/routes.rb
Rails.application.routes.draw do

  root 'countries#index'
  resources :countries, only: [:index, :show, :new, :create] do 
    get 'test' => 'countries#testing_map'
    get 'test_haml' => 'countries#test_map_haml'
    resources :regions, only: [:index, :show]
    resources :cities, only: [:index, :show, :new, :create]
  end

  resources :itineraries, only: [:index, :new, :create]
  resources :destinations

  resources :regions, only: [:new, :create]
end

app/views/global_partials/_sidebar.html.haml
#sidebar
  - if defined?(countries)
    %ul
      - countries.each do |country|
        %li.list-style-none= link_to country.native_language_name, country_path(country, anchor: "#{country.native_language_name}")
      %li.list-style-none= link_to "Back to Top", countries_path(anchor: "top")
  - elsif defined?(regions)
    %ul
      - regions.each do |region|
        %li.list-style-none= link_to region.native_language_name, country_regions_path(region.country, anchor: "#{region.native_language_name}")
      %li.list-style-none= link_to "Back to Top", country_regions_path(regions.first.country, anchor: "top")
  - elsif defined?(cities)
    %ul
      - cities.each do |city|
        %li.list-style-none= link_to city.native_language_name, country_cities_path(city.region.country, anchor: "#{city.native_language_name}")
      %li.list-style-none= link_to "Back to Top", country_cities_path(cities.first.region.country, anchor: "top")
      

app/views/global_partials/_sub_header.html.haml
- if country.present?
  %p
    .margin-quarter-bottom.inline= link_to "Add a Region", new_region_path, class: "btn btn-success btn-sm"
    .margin-quarter-bottom.inline= link_to "Add a City", new_country_city_path(country), class: "btn btn-success btn-sm"
%p
  .margin-quarter-top.inline= link_to "Add an Itinerary", new_itinerary_path(Itinerary.new), class: "btn btn-success btn-sm"
  .inline= link_to "Add a Destination", new_destination_path(Destination.new), class: "btn btn-success btn-sm"