config/routes.rb
Rails.application.routes.draw do

  root 'countries#index'
  resources :countries, only: [:index, :show, :new, :create] do 
    get 'test' => 'countries#testing_map'
    get 'test_haml' => 'countries#test_map_haml'
    resources :regions, only: [:index, :show]
    resources :cities, only: [:index, :show, :new, :create]
  end

  resources :itineraries, only: [:index, :new, :create]
  resources :destinations

  resources :regions, only: [:new, :create]
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :regions

  validates :native_language_name, presence: true, uniqueness: true
  
  validates :english_name, presence: true
  validates :country_website, url: true
  validates :description, length: {
    maximum: 400,
    tokenizer: lambda { |str| str.scan(/\w+/) },
    too_short: "must have at least %{count} words.",
    too_long: "must have less than %{count} words."
  }

  UNITED_STATES = ["united states", "the united states of america", "the united states", "usa", "the us", "us"]
  ITALY = ["italy", "italia", "the italy", "l'italia"]

  def find_cities_in_a_country
    cities = []
    self.regions.each do |region|
      cities << region.cities
    end
    cities.flatten
  end

  def united_states?
    Country::UNITED_STATES.include?(english_name.downcase)
  end

  def italy?
    Country::ITALY.include?(english_name.downcase) || Country::ITALY.include?(native_language_name.downcase)
  end

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

  def index
    @countries = Country.all
  end

  def show
    @country = Country.find(params[:id])
    @regions = @country.regions
    @cities = @country.find_cities_in_a_country

    @country_partial = country_partial(@country)
  end

  def all_cities
    @cities = City.all
    @country = Country.find(params[:id])

    render "cities/index"
  end

  def new
    @country = Country.new
  end

  def create
    @country = Country.new(country_params)
    if @country.save
      redirect_to country_path(@country)
    else
      render :'countries/new'
    end
  end

  def update

  end

  def test_map_haml
  end

  def testing_map
  end

  private

  def country_params
    params.require(:country).permit(:english_name, :native_language_name, :description, :country_website)
  end

  def all_cities_params
    params.require(:country).permit(:id).merge(region_id: "")
  end

  def country_partial(country)
    if country.united_states?
      return "united_states"
    else
      return "#{country.english_name.parameterize.underscore}"
    end
  end
end

app/views/countries/all_cities.html.haml
%h2 Cities
- @cities.each do |city|
  - params[:region_id] = city.region.id
  - params[:id] = city.id
  - params[:country_id] = city.region.country.id
  = link_to city.english_name, country_region_city_path(city.region.id, city)
  

app/views/countries/index.html.haml
%h2 Countries
 
- if @countries
  .row
    .col-md-2
      = render partial: "global_partials/sidebar", locals: { country: @country,countries: @countries}
    .col-md-10
      - @countries.each do |country|
        .media.margin-all
          .media-left
            = image_tag "italy-thumbnail.png", class: "media-object"
          .media-body.padding-left
            %h4.media-heading
              = link_to country.native_language_name, country_path(country), id: "#{country.native_language_name}"
              - if country.english_name != country.native_language_name
                = "(#{country.english_name})"
            = country.description
            %p.margin-half-top= link_to country.country_website, country.country_website, target: '_blank'

%hr
%h3 Add a new Country
= link_to "Add a Country", new_country_path, class: "btn btn-success btn-sm"

app/views/countries/new.html.haml
%h2 Add a Country

.inner-div
  = form_for(@country) do |f|
    - if @country.errors.any?
      Your country couldn't be saved because:
      %ul
        - @country.errors.messages.each do |field, error|
          %li.errors-colors= "#{field.to_s.titleize} #{error[0]}"

    .form-group
      = f.label :english_name, "Name in English"
      = f.text_field :english_name, class: "form-control"

    .form-group
      = f.label :native_language_name, "Name in Native Language"
      = f.text_field :native_language_name, class: "form-control" 

    .form-group
      = f.label :description, "Description (400 words or fewer)"
      = f.text_area :description, class: "form-control"

    .form-group
      = f.label :country_website, "Country Website (if any)"
      = f.text_field :country_website, class: "form-control"

    .form-group
      = f.submit "Save", class: "btn btn-default"

app/views/countries/show.html.haml
.row.border-bottom.padding-half-bottom
  .col-md-8
    %h2.no-spacing
      = @country.native_language_name 
      - if @country.english_name != @country.native_language_name
        %h4.italic.inline.no-spacing= "(english: #{@country.english_name})"
  .col-md-4
    = render partial: "global_partials/sub_header", locals: { country: @country }

.row
  .margin-top        
    = render partial: "countries/country_partials/#{@country_partial}"

  .margin-top 
  - if @country.united_states?
    %h3 States
  - else
    %h3 
      = link_to "Regions", country_regions_path(@country)
  %ul
  - @regions.each do |region|
    %li 
      =link_to region.english_name, country_region_path(@country, region)

  %h3.margin-top 
    = link_to "Cities", country_cities_path(@country)
  %ul
  - @cities.each do |city|
    %li 
      =link_to city.english_name, country_city_path(@country, city)

app/views/countries/test_map_haml.html.haml
= image_tag "italy-regions.gif", height: "750", width: "600", usemap: "#regions"
%map{ name: "regions", id: "regions"}
  %area.border{ href: "#", title: "Toscana", shape: "poly", cords: "137,145,142,140,145,139,151,146,159,151,164,153,169,159,173,157,180,162,185,160,187,163,193,160,192,157,200,154,206,157,207,160,212,159,210,166,212,175,221,177,223,180,233,179,235,182,231,186,226,193,226,195,223,198,229,204,223,207,223,209,219,214,220,224,213,231,214,237,208,243,205,242,205,247,200,252,190,250,186,253,183,251,188,246,187,242,184,240,181,237,180,233,172,231,174,224,170,222,167,220,162,224,163,215,164,207,162,202,159,196,155,192,155,183,156,175,153,167,150,163,147,160,145,154,142,154,137,145"}


= image_tag "http://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Map_of_USA_with_state_names.svg/800px-Map_of_USA_with_state_names.svg.png", width: "960", height: "593", usemap: "#usa"

%map{ name: "usa" }

  %area{ href: "#", title: "SC", shape: "poly", coords: "735,418, 734,419, 731,418, 731,416, 729,413, 727,411, 725,410, 723,405, 720,399, 716,398, 714,396, 713,393, 711,391, 709,390, 707,387, 704,385, 699,383, 699,382, 697,379, 696,378, 693,373, 690,373, 686,371, 684,369, 684,368, 685,366, 687,365, 687,363, 693,360, 701,356, 708,355, 724,355, 727,356, 728,360, 732,359, 745,358, 747,358, 760,366, 769,374, 764,379, 762,385, 761,391, 759,392, 758,394, 756,395, 754,398, 751,401, 749,404, 748,405, 744,408, 741,409, 742,412, 737,417, 735,418" }

:javascript 
  $('area').click(function(){
    console.log("area clicked")
    alert('foo');
  });