config/routes.rb
Rails.application.routes.draw do

  root 'countries#index'
  resources :countries, only: [:index, :show, :new, :create] do 
    get 'test' => 'countries#testing_map'
    get 'test_haml' => 'countries#test_map_haml'
    resources :regions, only: [:index, :show]
    resources :cities, only: [:index, :show, :new, :create]
  end

  resources :itineraries, only: [:index, :new, :create]
  resources :destinations

  resources :regions, only: [:new, :create]
end

app/models/region.rb
class Region < ActiveRecord::Base
  has_many :cities
  belongs_to :country 

  validates :country_id, presence: true, numericality: { only_integer: true }
  validates :native_language_name, presence: true, uniqueness: true

  validates :english_name, presence: true
  validates :region_website, url: true
  validates :description, length: {
    maximum: 400,
    tokenizer: lambda { |str| str.scan(/\w+/) },
    too_short: "must have at least %{count} words.",
    too_long: "must have less than %{count} words."
  }

end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController

  def index
    @country = Country.find(params[:country_id])
    @regions = @country.regions
  end

  def show
    @country = Country.find(params[:country_id])
    @region = Region.find(params[:id])
    @cities = @region.cities
  end

  def new
    @region = Region.new
  end

  def create
    @region = Region.new(strong_regions)

    if @region.save 
      redirect_to country_region_path(@region.country, @region)
    else
      render :'regions/new'
    end
  end

  private

  def strong_regions
    params.require(:region).permit(:english_name, :native_language_name, :description, :region_website, :country_id)
  end
end

app/views/regions/index.html.haml
.row.border-bottom.margin-bottom.padding-half-bottom
  .col-md-8
    %h2.no-spacing 
      = "Regions in #{@country.english_name}"
  .col-md-4
    = render partial: "global_partials/sub_header", locals: { country: @country, region: nil}


- if @regions
  .row
    .col-md-2
      = render partial: "global_partials/sidebar", locals: { regions: @regions}
    .col-md-10
      - @regions.each do |region|
        .media.margin-all
          .media-left
            = image_tag "italy-thumbnail.png", class: "media-object"
          .media-body.padding-left
            %h4.media-heading
              = link_to region.native_language_name, country_region_path(@country, region), id: "#{region.native_language_name}"
              - if region.english_name != region.native_language_name
                = "(#{region.english_name})"
            = region.description
            %p.margin-half-top= link_to region.region_website, region.region_website, target: '_blank'
- else
  %p.margin-top= "We're sorry! There isn't any region information for #{@country.english_name}"

app/views/regions/new.html.haml
%h2 Add a Region

.inner-div
  = form_for(@region, url: regions_path) do |f|
    - if @region.errors.any?
      Your region couldn't be saved because:
      %ul
        - @region.errors.messages.each do |field, error|
          %li.errors-colors= "#{field.to_s.capitalize} #{error[0]}"

    .form-group
      = f.label :country_id, "Select a Country"
      = f.collection_select :country_id, Country.all, :id, :english_name

    .form-group
      = f.label "Name in English"
      = f.text_field :english_name, class: "form-control"

    .form-group
      = f.label "Name in Native Language"
      = f.text_field :native_language_name, class: "form-control" 

    .form-group
      = f.label "Description (400 words or fewer)"
      = f.text_area :description, class: "form-control"

    .form-group
      = f.label "Region Website (if any)"
      = f.text_field :region_website, class: "form-control"

    .form-group
      = f.submit "Save", class: "btn btn-default"

app/views/regions/show.html.haml
.row.border-bottom.margin-bottom.padding-half-bottom
  .col-md-8
    %h2.no-spacing
      = link_to @region.native_language_name, country_regions_path(@country)
      - if @region.english_name != @region.native_language_name
        %h4.italic.inline.no-spacing= "(english: #{@region.english_name})"
  .col-md-4
    = render partial: "global_partials/sub_header", locals: { country: @country, region: @region}

// Country ------------------------------------
.row.padding-half-bottom
  .col-md-3
    %h4= Country
  .col-md-9
    = link_to @country.native_language_name, country_path(@country)
    .italic.inline.no-spacing= "(english: #{@country.english_name})" if @country.english_name != @country.native_language_name

// Description ------------------------------------
.row.padding-half-bottom
  .col-md-3
    %h4= "About #{@region.native_language_name}"
  .col-md-9
    %p= @region.description

// Website ------------------------------------
.row.padding-half-bottom.border-bottom
  .col-md-3
    %h4 Website
  .col-md-9
    %p= link_to "#{@region.region_website}", @region.region_website

- if @cities.any?
  %h2 Cities 
  %ul
  - @cities.each do |city| 
    %li
      = link_to city.native_language_name, country_city_path(@country, city) 
      .italic.inline= "(#{city.english_name})" if city.english_name != city.native_language_name
      = " - capital" if city.is_capital
- else
  %h4.margin-top 
    I'm sorry, there are no cities for this region yet. Please 
    = link_to "add one!", new_country_city_path(@country)
    