config/routes.rb
Rails.application.routes.draw do

  root 'countries#index'
  resources :countries, only: [:index, :show, :new, :create] do 
    get 'test' => 'countries#testing_map'
    get 'test_haml' => 'countries#test_map_haml'
    resources :regions, only: [:index, :show]
    resources :cities, only: [:index, :show, :new, :create]
  end

  resources :itineraries, only: [:index, :new, :create]
  resources :destinations

  resources :regions, only: [:new, :create]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Italia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>

    <%= link_to image_path root_url do %>

      <% country_id = '' %>
      <% if params["country_id"].presence %>
        <% country_id = params["country_id"] %>
      <% else %>
        <% country_id = params["id"] if params["controller"] == "countries" %>
      <% end %>

      <% if country_id.present? %>
        <% if Country.find(country_id).united_states? %>
          <%= image_tag "whitehouse_0.jpg", style: "width: 100%", id: "top" %>
        <% elsif Country.find(country_id).italy? %>
          <%= image_tag "piemonte-landscape-header.jpeg", style: "width: 100%", id: "top" %>
        <% end %>
      <% else %>
        <%= image_tag "general-travel-header.jpg", style: "width: 100%", id: "top" %>
      <% end %>

    <% end %>

    <div id="body">
      <div class="margin-bottom">
        <div class="margin-right inline">
          <h4 class="inline"><%= link_to "Home", root_path %></h4>
        </div>
        <div class="margin-right inline">
          <h4 class="inline"><%= link_to "Countries", countries_path %></h4>
        </div>
        <div class="margin-right inline">
          <h4 class="inline"><%= link_to "Itineraries", itineraries_path %></h4>
        </div>
        <div class="margin-right inline">
          <h4 class="inline"><%= link_to "Destinations", destinations_path %></h4>
        </div>
      </div>

      <%= yield %>
    </div>

</body>
</html>

app/views/layouts/mercury.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, maximum-scale=1.0, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <title>Mercury Editor</title>
    <%= stylesheet_link_tag    'mercury', 'mercury_overrides' %>
    <%= javascript_include_tag 'mercury', 'mercury_overrides' %>
  </head>
  <body>
    <script type="text/javascript">
      var saveUrl = null; // Set to the url that you want to save any given page to.
      var options = {
        saveStyle: null,  // 'form', or 'json' (default json)
        saveMethod: null, // 'POST', or 'PUT', (create, vs. update -- default POST)
        visible: null     // if the interface should start visible or not (default true)
      };

      <!-- Mix in any configurations provided through Rails.application.config.mercury_config -->
      <% if Rails.application.config.respond_to?(:mercury_config) %>
        jQuery.extend(Mercury.config, <%= Rails.application.config.mercury_config.to_json.html_safe %>);
      <% end -%>

      <!-- Mix in any options for PageEditor provided through Rails.application.config.mercury_page_editor_config -->
      <% if Rails.application.config.respond_to?(:mercury_page_editor_config) %>
        jQuery.extend(options, <%= Rails.application.config.mercury_page_editor_config.to_json.html_safe %>);
      <% end -%>

      <!-- Instantiate the PageEditor -->
      new Mercury.PageEditor(saveUrl, options);
    </script>
  </body>
</html>